version: "{build}"
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
nuget:
  disable_publish_on_pr: true
before_build:
- ps: >-
   dotnet tool install -g housework

    dotnet restore src/Config.Net.sln

    cd src/Config.Net

    housework setbuildnumber %FileVersion% -s ../../build.ini -v

    housework author ../*.csproj -s ../../build.ini -r -v

    cd ../..
build:
  project: src/Config.Net.sln
  verbosity: minimal
test_script:
- cmd: dotnet test .\src\Config.Net.Tests\
artifacts:
- path: src/**/*.nupkg
deploy: off