version: 4.7.1
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
nuget:
  disable_publish_on_pr: true
before_build:
- ps: .\appveyor.ps1
build:
  project: src/Config.Net.sln
  verbosity: minimal
test_script:
- cmd: dotnet test .\src\Config.Net.Tests\
artifacts:
- path: src/**/*.nupkg
deploy: off